name: Anomaly Detection Release tests workflow in Bundled OpenSearch Dashboards (Windows)
on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']

jobs:
  tests:
    uses: ./.github/workflows/release-e2e-workflow-template-windows.yml
    with:
      test-name: Anomaly Detection
      test-command: yarn cypress:run-with-security --browser chrome --spec 'cypress/integration/plugins/anomaly-detection-dashboards-plugin/overview_spec.js,cypress/integration/plugins/anomaly-detection-dashboards-plugin/vis_augmenter/associate_detector_spec.js'
