name: Index pattern without field FT
on: push

jobs:
  #   changes:
  #     runs-on: ubuntu-latest
  #     outputs:
  #       tests: ${{ steps.filter.outputs.tests }}
  #     steps:
  #       - uses: dorny/paths-filter@v2
  #         id: filter
  #         with:
  #           filters: |
  #             tests:
  #               - 'cypress/**/core-opensearch-dashboards/**'

  tests-with-security:
    # needs: changes
    ## if: ${{ needs.changes.outputs.tests == 'true' }}
    uses: ./.github/workflows/release-e2e-workflow-template.yml
    with:
      test-name: Index pattern without field with security
      test-command: env CYPRESS_ML_COMMONS_DASHBOARDS_ENABLED=true CYPRESS_VISBUILDER_ENABLED=true CYPRESS_DATASOURCE_MANAGEMENT_ENABLED=true yarn cypress:run-with-security --browser electron --spec 'cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/index_pattern_without_field.spec.js'
      osd-serve-args: --data_source.enabled=true --vis_builder.enabled=true --ml_commons_dashboards.enabled=true

  tests-without-security:
    # needs: changes
    ## if: ${{ needs.changes.outputs.tests == 'true' }}
    uses: ./.github/workflows/release-e2e-workflow-template.yml
    with:
      test-name: Index pattern without field without security
      test-command: env CYPRESS_ML_COMMONS_DASHBOARDS_ENABLED=true CYPRESS_VISBUILDER_ENABLED=true CYPRESS_DATASOURCE_MANAGEMENT_ENABLED=true yarn cypress:run-without-security --browser electron --spec 'cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/index_pattern_without_field.spec.js'
      osd-serve-args: --data_source.enabled=true --vis_builder.enabled=true --ml_commons_dashboards.enabled=true
      security-enabled: false
